# Note: With the introduction of workspaces we recommend using workspaces with APIOps when possible to limit what can be extracted whenever possible. 
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

# apiNames:
#  - echo-api
#  - test-api

 #backendNames:
 # - backendName1
 # - backendName2

 #diagnosticNames:
 #- diagnosticName1
 #- diagnosticName2

 #loggerNames:
 # - loggerName1
 # - loggerName2

 namedValueNames:
  - pruebagit
#  - prueba1

 productNames:
#  - starter
#  - unlimited

 subscriptionNames:
 #- 663a810511210e0054070001
 #- 663a810511210e0054070002

 #tagNames:
 # - tagName1
 # - tagName2
  
 #policyFragmentNames:
 # - policyFragment1
 # - policyFragment2